import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { database } from '../firebaseConfig';
import {
  collection,
  addDoc,
  getDocs,
  doc,
  updateDoc,
  deleteDoc
} from 'firebase/firestore';
import { useRouter } from 'next/router';
export default function Home() {
  const [ID, setID] = useState(null);
  const [name, setName] = useState('');
  const [age, setAge] = useState(null);
  const [weight, setWeight] = useState(null);
  const [fireData, setFireData] = useState([]);
  const [isUpdate, setIsUpdate] = useState(false);
//   const databaseRef = collection(database,'medicalsheet1');
  let router = useRouter()
  useEffect(() => {
    let token = sessionStorage.getItem('Token')
    if (token) {
      getData()
    }
    if (!token) {
      router.push('/register')
    }
  }, [])

  const addData = () => {
    addDoc(collection(database,'medicalsheet1'), {
      name: name,
      age: Number(age),
	  weight: Number(weight)

    })
      .then(() => {
        alert('Data Sent')
        getData()
        setName('')
        setAge(null)
		setWeight(null)
      })
      .catch((err) => {
        console.error(err);
      })
  }

  const getData = async () => {
    await getDocs(collection(database,'medicalsheet1'))
      .then((response) => {
        setFireData(response.docs.map((data) => {
          return { ...data.data(), id: data.id }
        }))
      })
  }

  const getID = (id, name, age, weight) => {
    setID(id)
    setName(name)
    setAge(age)
	setWeight(weight)
    setIsUpdate(true)
  }

  const updateFields = () => {
    let fieldToEdit = doc(database, 'medicalsheet1', ID);
    updateDoc(fieldToEdit, {
      name: name,
      age: Number(age),
	  weight: Number(weight) 

    })
    .then(() => {
      alert('Data Updated')
      getData()
      setName('')
      setAge(null)
      setIsUpdate(false)
    })
    .catch((err) => {
      console.log(err);
    })
  }

  const deleteDocument = (id) => {
    let fieldToEdit = doc(database, 'medicalsheet1', id);
    deleteDoc(fieldToEdit)
    .then(() => {
      alert('Data Deleted')
      getData()
    })
    .catch((err) => {
      alert('Cannot Delete that field..')
    })
  }

  const logout = () => {
    sessionStorage.removeItem('Token')
    router.push('/register')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Medical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={logout}>Log Out</button>
        </div>
        <h1>Home</h1>

        <input
          placeholder='Name'
          className={styles.inputBox}
          type="text"
          value={name}
          onChange={event => setName(event.target.value)}
        />
        <input
          placeholder='Age'
          className={styles.inputBox}
          type="number"
          value={age}
          onChange={event => setAge(event.target.value)}
        />

		<input
          placeholder='weight'
          className={styles.inputBox}
          type="number"
          value={weight}
          onChange={event => setWeight(event.target.value)}
        />

        {isUpdate ? (
          <button
            className={styles.button}
            onClick={updateFields}
          >
            UPDATE
          </button>
        ) : (
          <button
            className={styles.button}
            onClick={addData}
          >
            ADD
          </button>
        )}

        <div>
          {fireData.map((data) => {
            return (
              <div className={styles.flex}>
                <h3>Name: {data.name}</h3>
                <p>Age: {data.age}</p>
				<p>Weight: {data.weight}</p>
                <button
                  className={styles.button}
                  onClick={() => getID(data.id, data.name, data.age, data.weight)}
                >Update</button>
                <button
                  className={styles.button}
                  onClick={() => deleteDocument(data.id)}
                >Delete</button>
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}